In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_excel('../data/Online Retail.xlsx')

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.shape

(541909, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [7]:
df.duplicated().sum()

np.int64(5268)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    536641 non-null  object
 1   StockCode    536641 non-null  object
 2   Description  535187 non-null  object
 3   Quantity     536641 non-null  int64
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      536641 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 36.8+ MB

In [10]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [11]:
df=df.dropna(subset=['Description'])

In [12]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133583
Country             0
dtype: int64

In [13]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,535187.000000,535187,535187.000000,401604.000000
mean,9.671593,2011-07-04 11:43:44.485273600,4.645242,15281.160818
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13939.000000
50%,3.000000,2011-07-19 15:38:00,2.080000,15145.000000
75%,10.000000,2011-10-19 08:20:00,4.130000,16784.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,219.059056,NaN,97.364810,1714.006089

In [14]:
df.nunique()

InvoiceNo      24446
StockCode       3958
Description     4223
Quantity         671
InvoiceDate    22309
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535187 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    535187 non-null  object
 1   StockCode    535187 non-null  object
 2   Description  535187 non-null  object
 3   Quantity     535187 non-null  int64
 4   InvoiceDate  535187 non-null  datetime64[ns]
 5   UnitPrice    535187 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      535187 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 36.7+ MB

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535187 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    535187 non-null  object
 1   StockCode    535187 non-null  object
 2   Description  535187 non-null  object
 3   Quantity     535187 non-null  int64
 4   InvoiceDate  535187 non-null  datetime64[ns]
 5   UnitPrice    535187 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      535187 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 36.7+ MB

In [18]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [19]:
df = df.dropna(subset=['CustomerID'])

In [20]:
df['CustomerID'] = df['CustomerID'].astype(int)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  int64
 7   Country      401604 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 27.6+ MB

In [22]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [23]:
negative_qty = df[df['Quantity'] < 0]
print(f"عدد الصفوف بـ Quantity سالبة: {len(negative_qty)}")
negative_qty.head()

عدد الصفوف بـ Quantity سالبة: 8872

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom

In [25]:
df = df[df['Quantity'] > 0]

print(df.shape)
print((df['Quantity'] < 0).sum())  # المفروض يطلع 0

(392732, 8)
0

In [26]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,392732.000000,392732,392732.000000,392732.000000
mean,13.153718,2011-07-10 19:15:24.576301568,3.125596,15287.734822
min,1.000000,2010-12-01 08:26:00,0.000000,12346.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000
std,181.588420,NaN,22.240725,1713.567773

In [27]:
# نشوف القيمة الغريبة دي جاية منين
df[df['UnitPrice'] > 1000]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
117054,546328,M,Manual,1,2011-03-11 10:19:00,1687.17,14911,EIRE
117055,546329,M,Manual,1,2011-03-11 10:22:00,1687.17,14911,EIRE
144826,548813,M,Manual,1,2011-04-04 13:03:00,2382.92,12744,Singapore
144828,548813,M,Manual,1,2011-04-04 13:03:00,1252.95,12744,Singapore
144829,548820,M,Manual,1,2011-04-04 13:04:00,2053.07,12744,Singapore
145831,548913,M,Manual,1,2011-04-05 09:45:00,1136.30,12669,France
150615,549468,M,Manual,1,2011-04-08 14:27:00,1867.86,17940,United Kingdom
173382,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029,United Kingdom
200745,554155,M,Manual,1,2011-05-23 11:26:00,1241.98,12757,Portugal
201553,554301,M,Manual,1,2011-05-23 14:46:00,1241.98,12757,Portugal
297438,562946,M,Manual,1,2011-08-11 09:38:00,2500.00,15581,United Kingdom
343000,566927,M,Manual,1,2011-09-15 15:20:00,2033.10,17846,United Kingdom
374542,569382,M,Manual,1,2011-10-03 16:44:00,3155.95,15502,United Kingdom
406406,571751,M,Manual,1,2011-10-19 11:18:00,3949.32,12744,Singapore
406407,571751,M,Manual,1,2011-10-19 11:18:00,2118.74,12744,Singapore
422351,573077,M,Manual,1,2011-10-27 14:13:00,4161.06,12536,France
422376,573080,M,Manual,1,2011-10-27 14:20:00,4161.06,12536,France
467436,576339,DOT,DOTCOM POSTAGE,1,2011-11-14 15:27:00,1500.36,14096,United Kingdom
494728,578270,DOT,DOTCOM POSTAGE,1,2011-11-23 13:39:00,1270.06,14096,United Kingdom
508459,579196,DOT,DOTCOM POSTAGE,1,2011-11-28 15:54:00,1526.76,14096,United Kingdom
528082,580727,DOT,DOTCOM POSTAGE,1,2011-12-05 17:17:00,1599.26,14096,United Kingdom

In [ ]:
df = df[~df['StockCode'].isin(['M', 'POST', 'DOT'])]

print(df.shape)
print(df[df['UnitPrice'] > 1000])

(391332, 8)
Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [29]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391332 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    391332 non-null  object
 1   StockCode    391332 non-null  object
 2   Description  391332 non-null  object
 3   Quantity     391332 non-null  int64
 4   InvoiceDate  391332 non-null  datetime64[ns]
 5   UnitPrice    391332 non-null  float64
 6   CustomerID   391332 non-null  int64
 7   Country      391332 non-null  object
 8   TotalPrice   391332 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 29.9+ MB

In [31]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

In [32]:
df.to_csv('../data/clean_online_retail.csv', index=False)